source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'
use_frameworks!

target 'OrderList' do
  # Comment the next line if you don't want to use dynamic frameworks
  # Pods for OrderList
  pod 'SnapKit', '~> 5.7.0'
end
